name: Deploy to GitHub Pages

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout the repository
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Install dependencies
        run: npm install

      - name: Build the Angular app
        run: node --max_old_space_size=4096 node_modules/@angular/cli/bin/ng build --configuration production --output-path=dist

      - name: Deploy to GitHub Pages
        env:
          GITHUB_TOKEN: ${{ secrets.ACTIONS_DEPLOY_TOKEN }}
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git remote set-url origin https://x-access-token:${{ secrets.ACTIONS_DEPLOY_TOKEN }}@github.com/${{ github.repository }}

          echo "Fetching gh-pages branch..."
          git fetch origin gh-pages || echo "gh-pages branch does not exist. Creating a new one."

          echo "Checking out gh-pages branch..."
          if git show-ref --quiet refs/remotes/origin/gh-pages; then
            git checkout gh-pages
          else
            git checkout --orphan gh-pages
          fi

          echo "Cleaning up old contents..."
          git rm -rf . || true

          echo "Copying new build output..."
          cp -r dist/* .

          echo "Staging new changes..."
          git add .

          echo "Committing changes..."
          git commit -m "Deploy to GitHub Pages"

          echo "Pushing to gh-pages branch..."
          git push origin gh-pages --force

          echo "Deployment completed."
